export {default as blog1} from "./blog1.png"
export {default as blog2} from "./blog2.png"
export {default as blog3} from "./blog3.png"
export {default as blog4} from "./blog4.png"
export {default as blog5} from "./blog5.png"
export {default as logo} from "./logo.svg"